Added default module_lang to fix pip unicode error
When installing a package (spurs) via pip, it was throwing the following
error: UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position
3190: ordinal not in range(128)

This was due to ansible defaulting to using 'C' as the module lang.